[package]
name = "dePoll"
version = "0.8.0"
edition = "2021"

[dependencies]
casper-contract = "3.0.0"
casper-types = "3.0.0"

[[bin]]
name = "contract"
path = "src/main.rs"
bench = false
doctest = false
test = false

[profile.release]
codegen-units = 1
lto = true
